#!/usr/bin/env bash

IDENT=$(aws sts get-caller-identity)
ARN=$(node -pe "JSON.parse(process.argv[1]).Arn" "$IDENT")
npx cdk deploy --app "ts-node ../aws-runtime-cdk/src/app.ts" ${CI:---hotswap} --require-approval never --outputs-file $OUTPUTS_FILE --context "assumeRole=$ARN"