#!/usr/bin/env bash

set -ex

export EVENTUAL_DEFAULT_SERVICE=eventual-tests

## start local as a daemon
{
  npx pm2 start --wait-ready --interpreter pnpm --name Local eventual -- local --entry 'test/test-service.ts' &&
  ## run the tests
  pnpm run test:local
} || {
  npx pm2 logs --nostream &&
  npx pm2 delete Local &&
  exit 1
}

## stop the server
npx pm2 delete Local