#!/usr/bin/env bash

set -ex

export EVENTUAL_DEFAULT_SERVICE=eventual-tests
export OUTPUTS_FILE=cdk.out/outputs.json

## start local as a daemon
{
  npx pm2 start --wait-ready --listen-timeout 100000 --interpreter pnpm --name Local eventual -- local --entry 'test/test-service.ts' --service eventual-tests --cdk ../aws-runtime/scripts/deploy &&
  ## run the tests
  pnpm run test:local
} || {
  npx pm2 logs --nostream &&
  npx pm2 delete Local &&
  exit 1
}

## stop the server
npx pm2 delete Local