#!/usr/bin/env bash

set -ex

export EVENTUAL_DEFAULT_SERVICE=eventual-tests

npx eventual list services

npx eventual list workflows

npx eventual start workflow sleepy

npx eventual start workflow sleepy -f

npx eventual list executions

npx eventual list executions --workflow sleepy --json > .eventual/out.json

execution_id=$(node -p 'JSON.parse(require("fs").readFileSync(".eventual/out.json").toString("utf8")).executions[0].id')

npx eventual get history -e ${execution_id}

npx eventual get logs --all

npx eventual get logs --workflow sleepy

npx eventual get logs --execution ${execution_id}

npx eventual replay execution ${execution_id}