#!/usr/bin/env bash

set -e

export EVENTUAL_DEFAULT_SERVICE=eventual-tests

npx eventual services

npx eventual workflows

npx eventual executions 

npx eventual executions --workflow parallel > .eventual/out.json

execution_id=$(node -p 'JSON.parse(require("fs").readFileSync(".eventual/out.json").toString("utf8"))[0].id')

npx eventual history ${execution_id}

npx eventual logs

npx eventual logs --workflow parallel

npx eventual logs --execution ${execution_id}

npx eventual start sleepy

npx eventual start sleepy --tail

npx eventual replay ${execution_id} 'test/test-service.ts'