/**
 * Commands Generated by the workflow to be executed by the engine.
 * 
 * Generate Events.
 */
export type Command = StartLocalActivityCommand;

export interface StartLocalActivityCommand {
  type: "StartLocalActivityCommand";
  counter: number;
}