export const TaskNameDimension = "TaskName";
/**
 * The age of the request, or the time from when it was sent to when it was started processing.
 */
export const TaskRequestAge = "TaskRequestAge";
/**
 * The amount of time it took to claim (lock) the task to enforce exactly once processing.
 */
export const ClaimDuration = "ClaimDuration";
/**
 * Whether this task invocation was rejected when claiming the task.
 */
export const ClaimRejected = "ClaimRejected";
/**
 * Whether an error was thrown that the task name could not be found.
 */
export const NotFoundError = "NotFoundError";
/**
 * The amount of time it took to run the task's code.
 */
export const OperationDuration = "OperationDuration";
/**
 * Whether this task returned a result or not on completion.
 */
export const HasResult = "HasResult";
/**
 * Returned {@link asyncResult}.
 */
export const AsyncResult = "AsyncResult";
/**
 * The size in bytes of the result generated by the task, if one was generated.
 */
export const ResultBytes = "ResultBytes";
/**
 * Whether the task completed with errors.
 */
export const TaskFailed = "TaskFailed";
/**
 * Whether the task completed without error.
 */
export const TaskSucceeded = "TaskSucceeded";
/**
 * The total duration of the task after being scheduled, including the time
 * waiting to be executed.
 */
export const TotalDuration = "TotalDuration";
/**
 * amount of time it took to submit a workflow task to SQS to resume the workflow.
 */
export const SubmitWorkflowTaskDuration = "SubmitWorkflowTaskDuration";
/**
 * Number of milliseconds it takes to send execution logs to where ever they are persisted.
 */
export const TaskLogWriteDuration = "TaskLogWriteMillis";
